const root=document.querySelector('#root'),dialog=document.querySelector('#editor');
const e=v=>String(v??'UNKNOWN').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session,reqs,profile,batch,uploaded,dirty=false,busy=false,notice='',offset=0,search='';
const can=action=>session?.permissions.includes(action);
async function api(url,method='GET',body,key) {
 const options={method,headers:{},credentials:'same-origin'};
 if(method!=='GET'){options.headers['X-CSRF-Token']=session?.csrf||'';options.headers['Idempotency-Key']=key||crypto.randomUUID();if(body instanceof FormData)options.body=body;else{options.headers['Content-Type']='application/json';options.body=JSON.stringify(body||{});}}
 let r;try{r=await fetch('/api/v1'+url,options);}catch{throw Error('সার্ভারের সাথে যোগাযোগ নেই। আপনার ইনপুট রাখা হয়েছে; Retry করুন।');}
 const data=await r.json();if(!r.ok){const error=Error(data.error||'পরিবর্তন সংঘাত: অন্য ব্যবহারকারী তথ্য বদলেছেন।');error.data=data;error.status=r.status;throw error;}return data;
}
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}" class="empty">এখনো কোনো রেকর্ড নেই।</td></tr>`}</tbody></table></div>`;
const button=(label,action,attrs='',primary=false)=>`<button ${primary?'class="primary"':''} data-action="${action}" ${attrs}>${label}</button>`;
const field=(name,label,type='text',value='',required=false)=>`<label>${label}<input name="${name}" type="${type}" value="${e(value??'')}" ${required?'required':''}></label>`;
const editButton=(type,id)=>can('edit')?button('Edit','edit',`data-type="${type}" data-id="${id}"`):'';
function layout(content,active='companies') {
 root.innerHTML=`<div class="shell"><aside class="rail"><div class="brand">GM PRINT<span class="tiny"> · FOUNDATION</span></div><nav><a class="${active==='companies'?'active':''}" href="#companies">Company intelligence</a><a href="#contacts">Contact search</a><a href="#imports" class="${active==='imports'?'active':''}">Data imports</a><a href="#audit">Activity & audit</a><a href="#features">Delivery status</a></nav><div class="module-links"><p><small>REQUIREMENT MAP · 16 MODULES</small></p>${(reqs||[]).map(m=>`<a href="#module/${m.id}">${e(m.id)} · ${e(m.title||m.name)}</a>`).join('')}</div><p><a href="/">Fictional demo ↗</a><small>Local D3 · PostgreSQL<br>ERP / outbound: Not connected</small></p></aside><main class="main" id="content"><header class="top"><div><span class="pill">Authenticated · Persistent data</span><p class="muted tiny">Company → Contacts → Provenance → Consent</p></div><div class="actions"><span>${e(session.user.username)} · ${e(session.user.role)}</span>${button('Logout','logout')}</div></header>${notice?`<div class="success" role="status">${e(notice)}</div>`:''}<div id="page-error" role="alert"></div>${content}</main></div>`;notice='';
}
async function boot(){try{session=await api('/session');reqs=await fetch('/requirements.json').then(r=>r.json());if(!session.user)return login();await render();}catch(err){root.innerHTML=`<main class="login panel"><h1>ডেটাবেজ সংযোগ পাওয়া যায়নি</h1><p class="error">${e(err.message)}</p>${button('Retry','boot')}</main>`;}}
function login(){root.innerHTML=`<main class="panel login" id="content"><span class="pill">GM Print · D3 local application</span><h1>আপনার workspace-এ প্রবেশ করুন</h1><p class="muted">Company ও contact ডেটা PostgreSQL-এ সংরক্ষিত হবে। Local setup-এর private credentials ব্যবহার করুন।</p><form id="login-form">${field('username','Username','text','',true)}${field('password','Password','password','',true)}<div class="error" hidden role="alert"></div><button class="primary">Login</button></form><p><a href="/">Fictional demo দেখুন ↗</a></p></main>`;}
async function render(){
 if(!session?.user)return login();const hash=location.hash.slice(1)||'companies';
 try {
  if(hash.startsWith('company/'))return await companyPage(hash.split('/')[1],hash.split('/')[2]||'overview');
  if(hash==='contacts'){profile=null;const data=await api('/contacts?q='+encodeURIComponent(search)+'&offset='+offset+'&limit=25');layout(`<h1>Contact search</h1><p>Contacts-এর current এবং historical company relationships</p><section class="panel"><form id="search-form" class="actions"><label>Contact name<input name="q" value="${e(search)}"></label><button>Search</button></form>${table(['Contact','Companies / roles'],data.rows.map(r=>`<tr><td>${e(r.name)}<small>${e(r.id)}</small></td><td>${r.relationships.map(x=>`<a href="#company/${x.company_id}/contacts">${e(x.company_name)}</a> · ${e(x.designation)} · ${e(x.valid_to||'Current')}`).join('<br>')}</td></tr>`))}${pager(data.rows.length,25)}</section>`);return;}
  if(hash==='imports')return await importsPage();
  if(hash.startsWith('import/'))return await importPage(hash.split('/')[1]);
  if(hash==='audit'){const data=await api('/audit?limit=50&offset='+offset);layout(`<h1>Persisted activity history</h1><p>Actor, timestamp ও redacted change references।</p><section class="panel">${table(['Time','Actor','Action','Resource','Result'],data.rows.map(r=>`<tr><td>${e(r.created_at)}</td><td>${e(r.actor)}</td><td>${e(r.action)}</td><td>${e(r.resource_type)}<small>${e(r.resource_id)}</small></td><td>${e(r.result)}</td></tr>`))}${pager(data.rows.length,50)}</section>`);return;}
  if(hash==='features'||hash.startsWith('module/')){const manifest=await fetch('/workspace/features.json').then(r=>r.json());const selected=hash.split('/')[1];layout(`<h1>${selected?e(selected)+' · Requirement status':'Delivery 3 scope'}</h1><p>Source coverage এবং operational completion আলাদা। Unimplemented modules এখানে business action চালায় না।</p>${manifest.modules.filter(m=>!selected||m.id===selected).map(m=>`<section class="panel"><span class="pill warn">${e(m.status)}</span><h2>${e(m.id)} · ${e(m.name)}</h2><p>${e(m.scope)}</p><p class="muted">${e(m.evidence)}</p>${(reqs.find(x=>x.id===m.id)?.subs||[]).map(s=>`<p><b>${e(s.id)} · ${e(s.title||s.name)}</b></p>`).join('')}</section>`).join('')}`);return;}
  const data=await api('/companies?limit=25&offset='+offset+'&q='+encodeURIComponent(search));
  layout(`<div class="hero"><div><p class="muted tiny">M05.S1–S4 · COMPANY-FIRST DATABASE</p><h1>Company intelligence</h1><p>একটি কোম্পানি, বহু contact, যাচাইযোগ্য উৎস।</p></div><div class="actions">${can('create')?button('+ Add company','new', 'data-type="company"',true):''}${can('export')?'<a class="btn" href="/api/v1/companies.csv">Export CSV</a>':''}</div></div><div class="grid"><section class="panel stat"><span>Search results · database total</span><strong>${data.total}</strong></section><section class="panel"><b>Quality before outreach</b><p class="muted">অজানা তথ্য UNKNOWN। Endpoint থাকলেই consent পাওয়া যায় না।</p></section></div><section class="panel"><form id="search-form" class="actions"><label>Company search<input name="q" value="${e(search)}" placeholder="কোম্পানির নাম"></label><button>Search</button></form>${table(['Company','Industry','Verification','Version'],data.rows.map(r=>`<tr><td><a href="#company/${r.id}/overview">${e(r.name)}</a><small>${e(r.id)}</small></td><td>${e(r.industry)}</td><td>${e(r.status)}</td><td>${r.version}</td></tr>`))}${pager(data.rows.length,25)}</section>`);
 }catch(err){layout(`<h1>লোড করা যায়নি</h1><div class="error">${e(err.message)}</div>${button('Retry','retry')}`);}
}
const pager=(count,limit)=>`<div class="pagination">${button('← Previous','prev',`data-limit="${limit}" ${offset===0?'disabled':''}`)}<span>Offset ${offset} · ${count} records</span>${button('Next →','next',`data-limit="${limit}" ${count<limit?'disabled':''}`)}</div>`;
async function companyPage(id,tab){
 profile=await api('/companies/'+id);const p=profile,c=p.company;
 const tabs=[['overview','Overview'],['hierarchy','Hierarchy / branches'],['contacts','Contacts / history'],['channels','Channels / consent'],['sources','Source / verification'],['activity','Activity']];
 let body='';
 if(tab==='overview')body=`<h2>Company overview ${editButton('company',id)}</h2><dl class="details">${['name','industry','address','website','status','version','id'].map(k=>`<dt>${e(k)}</dt><dd>${e(c[k])}</dd>`).join('')}<dt>ERP</dt><dd>Not connected · no ERP reference</dd></dl>`;
 if(tab==='hierarchy')body=`<div class="actions"><h2>Group: ${e(p.group?.name||'UNKNOWN')}</h2>${p.group?editButton('company_group',p.group.id):''}${can('create')?button('+ Group','new','data-type="company_group"')+button('+ Branch','new','data-type="branch"'):''}</div>${table(['Branch','Address','Action'],p.branches.map(b=>`<tr><td>${e(b.name)}</td><td>${e(b.address)}</td><td>${editButton('branch',b.id)}</td></tr>`))}<p class="muted">Company Edit থেকে group নির্বাচন করুন। Group/Company/Branch পৃথক রেকর্ড।</p>`;
 if(tab==='contacts')body=`<div class="actions"><h2>Contacts & role history</h2>${can('create')?button('+ Contact','new','data-type="contact"')+button('+ Relationship','new','data-type="contact_company_role"'):''}</div>${table(['Contact','Role / department','Validity','Action'],p.contacts.map(r=>`<tr><td>${e(r.name)}<small>${e(r.contact_id)}</small></td><td>${e(r.designation)}<small>${e(r.normalized_role)} · ${e(r.department)}</small></td><td>${e(r.valid_from)} → ${e(r.valid_to||'Current')}</td><td>${editButton('contact',r.contact_id)} ${editButton('contact_company_role',r.id)}</td></tr>`))}<p class="muted">চাকরি বদলালে পুরোনো role end-date করুন; নতুন company relationship যোগ করুন।</p>`;
 if(tab==='channels')body=`<div class="actions"><h2>Endpoints & permission</h2>${can('create')?button('+ Endpoint','new','data-type="channel_endpoint"')+button('+ Association','new','data-type="endpoint_association"'):''}</div>${table(['Channel','Value','Contact','Actions'],p.channels.map(r=>`<tr><td>${e(r.channel)}</td><td>${e(r.raw_value)}<small>Normalized: ${e(r.normalized_value)} · reachability ${e(r.reachability)}</small></td><td>${e(r.contact_id)}</td><td>${button('Eligibility','eligibility',`data-id="${r.id}" data-contact="${r.contact_id||''}"`)} ${can('withdraw')?button('Consent','consent',`data-id="${r.id}" data-contact="${r.contact_id||''}"`):''}</td></tr>`))}<h3>Consent history</h3>${table(['Time','Purpose','Status','Evidence'],p.consent.map(r=>`<tr><td>${e(r.created_at)}</td><td>${e(r.purpose)}</td><td>${e(r.status)}</td><td>${e(r.evidence)}</td></tr>`))}<p class="muted">Outbound dispatch disabled. Phone ≠ WhatsApp permission. Global suppression remains effective after reimport.</p>`;
 if(tab==='sources')body=`<h2>Field-level evidence</h2><p>Latest 200 observations; API supports paginated full history. Verified শুধু authorized evidence review-এর পরে।</p>${table(['Field / entity','Value','Source','Review'],p.observations.map(r=>`<tr><td>${e(r.field)}<small>${e(r.entity_type)} · ${r.selected?'Current':'Historical'}</small></td><td>${e(r.normalized_value)}<small>Raw: ${e(r.raw_value)} · ${e(r.knowledge_status)}</small></td><td>${e(r.source_type)} · ${e(r.reference)}<small>${e(r.sheet)} / row ${e(r.row_number)}<br>${e(r.collected_at)} · ${e(r.actor)}</small></td><td>${e(r.verification)}${(r.reviews||[]).map(d=>`<small>${e(d.reviewer)} · ${e(d.decision)} · ${e(d.created_at)}<br>${e(d.evidence)}</small>`).join('')}<small>Checked: ${e(r.last_checked)}</small>${can('review')&&r.knowledge_status!=='UNKNOWN'?button('Review','verify',`data-id="${r.id}"`):''}</td></tr>`))}`;
 if(tab==='activity')body=`<h2>Recent activity</h2>${table(['Time','Actor','Action','Resource / version'],p.activity.map(r=>`<tr><td>${e(r.created_at)}</td><td>${e(r.actor)}</td><td>${e(r.action)}</td><td>${e(r.resource_type)} · v${e(r.resource_version)}</td></tr>`))}<a href="#audit">Full paginated audit →</a>`;
 layout(`<a href="#companies">← Company directory</a><div class="hero"><div><h1>${e(c.name)}</h1><p>${e(c.industry)} · ${p.contacts.length} role relationships · v${c.version}</p></div><span class="pill warn">${e(c.status)}</span></div><nav class="tabs">${tabs.map(([key,label])=>`<a class="btn ${tab===key?'active':''}" href="#company/${id}/${key}">${label}</a>`).join('')}</nav><section class="panel">${body}</section>`);
}
const definitions={company:[['name','Company name'],['group_id','Company group','company_group'],['industry','Industry'],['address','Address'],['website','Website']],company_group:[['name','Group name']],branch:[['name','Branch name'],['company_id','Company','company'],['address','Address']],contact:[['name','Contact name']],contact_company_role:[['company_id','Company','company'],['contact_id','Contact','contact'],['branch_id','Branch (same company)','branch'],['designation','Original designation'],['normalized_role','Normalized role'],['department','Department'],['valid_from','Start date','date'],['valid_to','End date','date']],channel_endpoint:[['channel','Channel','channel'],['raw_value','Raw value']],endpoint_association:[['endpoint_id','Endpoint','channel_endpoint'],['company_id','Company','company'],['contact_id','Contact (optional)','contact']]};
function showDialog(title,content){dialog.innerHTML=`<h2 id="editor-title">${title}</h2>${content}`;dialog.showModal();dialog.querySelector('input,select,button')?.focus();}
async function entityForm(type,id){
 let data={},version;
 if(id){const candidates=[profile?.company,profile?.group,...(profile?.branches||[]),...(profile?.contacts||[])];data=candidates.find(c=>c?.id===id)||{};if(type==='contact'){const role=profile.contacts.find(r=>r.contact_id===id);data={name:role.name};version=role.contact_version;}else version=data.version;}
 const choices={};for(const[, ,kind]of definitions[type])if(kind&&kind!=='date'&&kind!=='channel')choices[kind]=(await api('/entities/'+kind+'?limit=100')).rows;
 const formFields=type==='contact'&&!id&&profile?[...definitions.contact,['designation','Designation'],['department','Department']]:definitions[type];
 const html=formFields.map(([key,label,kind])=>{
  const val=data[key]??(key==='company_id'?profile?.company.id:'')??'';
  if(choices[kind]||kind==='channel'){const opts=kind==='channel'?['Email','Phone','WhatsApp','Website','Social'].map(x=>({id:x,name:x})):choices[kind];return `<label>${label}<select name="${key}" ${['company_id','endpoint_id','channel'].includes(key)?'required':''}><option value="">Select / UNKNOWN</option>${opts.map(o=>`<option value="${o.id}" ${val===o.id?'selected':''}>${e(o.name||o.raw_value)} · ${e(o.id.slice(0,8))}</option>`).join('')}</select></label>`;}
  return field(key,label,kind==='date'?'date':'text',val,['name','raw_value'].includes(key));
 }).join('');
 showDialog(`${id?'Edit':'Add'} ${e(type)}`,`<form id="entity-form" data-type="${type}" data-id="${id||''}" data-version="${version||''}" data-key="${crypto.randomUUID()}"><div class="grid">${html}${field('source','Source / evidence note','text','',true)}</div><p class="tiny muted">Selectors show first 100 records. Values remain unverified until reviewed.</p><div class="error" hidden role="alert"></div><div class="actions"><button class="primary">Save to database</button>${button('Cancel','close')}</div></form>`);
}
async function importsPage(){profile=null;const data=await api('/imports');layout(`<div class="hero"><div><h1>Data import workspace</h1><p>M02.S1/S3 · private upload → mapping → review → transactional job</p></div></div>${can('import')?`<section class="panel"><h2>CSV / XLSX upload</h2><form id="upload-form"><label>Source file · max 5 MB<input type="file" name="file" accept=".csv,.xlsx" required></label><div class="actions"><button class="primary">Upload & inspect</button></div><div class="error" hidden></div></form></section>`:''}<section class="panel">${table(['Batch','State','Counts'],data.rows.map(r=>`<tr><td><a href="#import/${r.id}">${e(r.id)}</a><small>${e(r.created_at)}</small></td><td>${e(r.state)}</td><td>${e(JSON.stringify(r.counts))}</td></tr>`))}</section>`,'imports');}
function mappingForm(){const s=uploaded.sheets.find(s=>s.name===document.querySelector('#sheet')?.value)||uploaded.sheets[0];return `<form id="mapping-form" data-key="${crypto.randomUUID()}"><div class="grid"><label>Sheet<select id="sheet" name="sheet">${uploaded.sheets.map(x=>`<option ${s.name===x.name?'selected':''}>${e(x.name)}</option>`).join('')}</select></label>${field('namespace','Source system namespace','text','manual-list',true)}${Object.entries(uploaded.aliases).map(([k,aliases])=>`<label>${e(k)}<select name="map_${k}"><option value="">Not mapped</option>${s.headers.map(h=>`<option ${aliases.includes(h.toLowerCase())?'selected':''}>${e(h)}</option>`).join('')}</select></label>`).join('')}</div><div class="error" hidden></div><div class="actions"><button class="primary">Preview & validate</button></div></form>`;}
async function importPage(id){
 batch=await api('/imports/'+id+'?limit=100&offset='+offset);if(!uploaded||uploaded.id!==id)uploaded={id,sheets:batch.sheets,aliases:Object.fromEntries(['company','group','branch','source_id','canonical_id','contact','contact_id','designation','department','email','phone','website','social','address','industry','reference','consent'].map(k=>[k,[k]]))};
 layout(`<a href="#imports">← Import history</a><div class="hero"><div><h1>Import review</h1><p>${e(batch.reference)} · ${e(batch.state)} · mapping v${batch.mapping_version}</p></div>${button('Refresh job','retry')}</div>${batch.state==='Uploaded'&&uploaded?.id===id?`<section class="panel" id="mapping-panel">${mappingForm()}</section>`:''}${batch.state==='Uploaded'&&uploaded?.id!==id?'<p class="error">Sheet mapping metadata is not loaded. Re-upload the source to map it; identical committed imports remain repeat-safe.</p>':''}<section class="panel"><h2>Row counts / entity effects</h2><pre>${e(JSON.stringify(batch.counts,null,2))}</pre><div class="actions">${can('import')&&batch.state==='Preview'?button('Commit accepted rows','commit','',true):''}${can('import')&&['Committed','RollbackConflict'].includes(batch.state)?button('Safe rollback','rollback'):''}${can('export')?`<a class="btn" href="/api/v1/imports/${id}/errors.csv">Export row errors</a>`:''}</div>${table(['Row','Mapped values','Validation','Review'],batch.rows.map(r=>`<tr><td>${r.row_number}</td><td><pre>${e(JSON.stringify(r.data,null,2))}</pre></td><td>${e(r.status)}<small>${e(r.reason)}</small></td><td>${r.status==='needs-review'&&can('review')?button('Resolve identity','resolve',`data-id="${r.id}"`):''}</td></tr>`))}${pager(batch.rows.length,100)}</section><section class="panel"><h2>Background jobs</h2>${table(['Kind','State','Attempts','Error'],batch.jobs.map(j=>`<tr><td>${e(j.kind)}</td><td>${e(j.state)}</td><td>${j.attempts}</td><td>${e(j.error)}</td></tr>`))}<h3>Rollback effect ledger (first 100)</h3>${table(['Entity','ID','Undo','Conflict'],batch.effects.map(r=>`<tr><td>${e(r.entity_type)}</td><td>${e(r.entity_id)}</td><td>${r.undone?'Undone':'Retained'}</td><td>${e(r.conflict)}</td></tr>`))}</section>`,'imports');
}
document.addEventListener('click',async event=>{
 const b=event.target.closest('[data-action]');if(!b)return;event.preventDefault();if(busy)return;
 try{switch(b.dataset.action){
  case'boot':return boot();case'retry':return render();case'logout':await api('/logout','POST');session=await api('/session');return login();
  case'new':return entityForm(b.dataset.type);case'edit':return entityForm(b.dataset.type,b.dataset.id);
  case'close':if(dirty&&!confirm('অসম্পূর্ণ পরিবর্তন বাতিল করবেন?'))return;dirty=false;return dialog.close();
  case'prev':offset=Math.max(0,offset-Number(b.dataset.limit||25));return render();case'next':offset+=Number(b.dataset.limit||25);return render();
  case'verify':return showDialog('Review evidence',`<form id="review-form" data-id="${b.dataset.id}"><label>Decision<select name="status"><option>Verified</option><option>Rejected</option></select></label>${field('evidence','Evidence reference / review note','text','',true)}<div class="error" hidden></div><div class="actions"><button class="primary">Record review</button>${button('Cancel','close')}</div></form>`);
  case'consent':return showDialog('Consent / suppression',`<form id="consent-form" data-id="${b.dataset.id}" data-contact="${b.dataset.contact}">${field('purpose','Purpose (* = global withdrawal)','text','marketing',true)}<label>Status<select name="status"><option>OptedOut</option><option>Unknown</option>${can('review')?'<option>OptedIn</option>':''}</select></label>${field('evidence','Evidence reference','text','',true)}<p>Withdrawal blocks immediately. Regrant does not clear global suppression in D3.</p><div class="error" hidden></div><div class="actions"><button class="primary">Record consent event</button>${button('Cancel','close')}</div></form>`);
  case'eligibility':{const r=await api(`/endpoints/${b.dataset.id}/eligibility?purpose=marketing${b.dataset.contact?'&contact_id='+b.dataset.contact:''}`);return showDialog('Marketing eligibility',`<pre>${e(JSON.stringify(r,null,2))}</pre>${button('Close','close')}`);}
  case'commit':case'rollback':{const r=await api(`/imports/${batch.id}/${b.dataset.action}`,'POST',{version:batch.mapping_version});notice='Job '+r.state+' · '+r.id;return render();}
  case'resolve':return showDialog('Resolve ambiguous row',`<form id="resolve-form" data-id="${b.dataset.id}">${field('company_id','Existing canonical company UUID (or leave blank)')}${field('new_identity','New source ID (use same ID for same company rows)')}${field('contact_id','Existing contact UUID (when contact identity is ambiguous)')}<label>Distinct new contact confirmed<select name="new_contact"><option value="">No</option><option value="yes">Yes — reviewed distinct person</option></select></label>${field('evidence','Reviewer reason','text','',true)}<div class="error" hidden></div><div class="actions"><button class="primary">Resolve</button>${button('Cancel','close')}</div></form>`);
 }}catch(err){const box=document.querySelector('#page-error');if(box)box.innerHTML=`<div class="error">${e(err.message)}</div>`;}
});
document.addEventListener('submit',async event=>{
 const form=event.target;event.preventDefault();if(busy)return;busy=true;const submit=form.querySelector('button');submit.disabled=true;const error=form.querySelector('.error');if(error)error.hidden=true;
 const values=Object.fromEntries(new FormData(form));const key=form.dataset.key||(form.dataset.key=crypto.randomUUID());
 try{
  switch(form.id){
   case'login-form':await api('/login','POST',values);session=await api('/session');await render();break;
   case'search-form':search=values.q;offset=0;await render();break;
   case'entity-form':{const source=values.source;delete values.source;for(const k of Object.keys(values))if(values[k]==='')values[k]=null;if(!values.valid_from)delete values.valid_from;const id=form.dataset.id;const linked=form.dataset.type==='contact'&&!id&&profile;const r=linked?await api('/companies/'+profile.company.id+'/contacts','POST',{...values,source},key):await api('/entities/'+form.dataset.type+(id?'/'+id:''),id?'PATCH':'POST',{data:values,source,...(id?{version:Number(form.dataset.version)}:{})},key);dirty=false;dialog.close();notice='Database-এ সংরক্ষিত · '+r.id;if(form.dataset.type==='company'&&location.hash!=='#company/'+r.id+'/overview')location.hash='company/'+r.id+'/overview';else await render();break;}
   case'review-form':await api('/observations/'+form.dataset.id+'/review','POST',values,key);dirty=false;dialog.close();notice='Review decision সংরক্ষিত';await render();break;
   case'consent-form':await api('/consent','POST',{...values,endpoint_id:form.dataset.id,contact_id:form.dataset.contact||null},key);dirty=false;dialog.close();notice='Consent event সংরক্ষিত';await render();break;
   case'upload-form':uploaded=await api('/imports','POST',new FormData(form));offset=0;location.hash='import/'+uploaded.id;break;
   case'mapping-form':{const mapping=Object.fromEntries(Object.entries(values).filter(([k,v])=>k.startsWith('map_')&&v).map(([k,v])=>[k.slice(4),v]));const r=await api('/imports/'+batch.id+'/preview','POST',{sheet:values.sheet,mapping,namespace:values.namespace,version:batch.mapping_version},key);if(r.duplicate_batch)location.hash='import/'+r.duplicate_batch;else await render();break;}
   case'resolve-form':{for(const k of ['company_id','new_identity','contact_id'])if(!values[k])delete values[k];values.new_contact=values.new_contact==='yes';await api(`/imports/${batch.id}/rows/${form.dataset.id}/resolve`,'POST',{...values,version:batch.mapping_version},key);dirty=false;dialog.close();await render();break;}
  }
 }catch(err){if(error){error.hidden=false;error.innerHTML=e(err.message)+(err.data?.fields?'<pre>'+e(JSON.stringify(err.data.fields,null,2))+'</pre>':'')+(err.data?.conflict?`<h3>Current (v${e(err.data.current.version)})</h3><pre>${e(JSON.stringify(err.data.current,null,2))}</pre><h3>Your proposed values (preserved)</h3><pre>${e(JSON.stringify(err.data.proposed,null,2))}</pre><p>Close করে reload করুন, তারপর নতুন version-এ প্রয়োজনীয় edit দিন।</p>`:'');error.focus();}form.dataset.key=err.status&&err.status<500?crypto.randomUUID():key;}
 finally{busy=false;submit.disabled=false;}
});
document.addEventListener('input',event=>{if(event.target.closest('dialog'))dirty=true;});
dialog.addEventListener('cancel',event=>{if(dirty&&!confirm('অসম্পূর্ণ পরিবর্তন বাতিল করবেন?'))event.preventDefault();else dirty=false;});
document.addEventListener('change',event=>{if(event.target.id==='sheet')document.querySelector('#mapping-panel').innerHTML=mappingForm();});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
window.addEventListener('hashchange',()=>{offset=0;render();});
boot();
